### ISSUE TITLE
[UX/UI] Criação de paleta de cores Training Center

### ISSUE THREAD

**Issue by fernandofleury** [training-center/R2D2#27]
Precisamos da paleta como trabalho inicial para derivar os próximos componentes pra plataforma

**Comment by istiu** [comment]
A paleta de cores geralmente se baseia nas cores do logo.
Nesse caso vamos usar o próprio logo do TC ou algum outro "genérico", deixando livre o uso de qualquer paleta?

**Comment by fernandofleury** [comment]
Livre.

**Comment by angelilton** [comment]
vai seguir essas cores? 
![color-trainingcenter](https://user-images.githubusercontent.com/16200828/31644860-00b70794-b2cf-11e7-9c0c-d666fc9dd5b6.PNG)

**Comment by alinebastos** [comment]
Eu estava tentando usar as cores do brand guide no header que eu construí (mal e porcamente, haha):
https://github.com/training-center/brand-guide

**Comment by fernandofleury** [comment]
@alinebastos não acho que seja má ideia usar não. mas faltam algumas cores pra fazermos ações complementares (pelo menos parece)

**Comment by alinebastos** [comment]
Concordo! :)

**Comment by woliveiras** [comment]
Galera, vai rolar uma mudança nas cores do Training Center logo menos. Nossos(as) @training-center/designers estão trabalhando nisso. :grin: 

Vai ter mudança no logo. Vai ser ano novo e vida nova.

**Comment by allangrds** [comment]
Então fica a questão @woliveiras: vamos definir uma paleta com o logo atual ou esperaremos ele ser remodelado?

**Comment by adeonir** [comment]
@allangrds o logo está quase, pretendo atualizar o repositório hoje.

**Comment by allangrds** [comment]
@adeonir Então é esse https://avatars1.githubusercontent.com/u/18053262?s=200&v=4 ?

**Comment by angeliski** [comment]
Opa @adeonir O logo ficou legal hein? Você acha que a gente consegue definir o esquema de cores agora?

**Comment by alinebastos** [comment]
As cores e logos estão todos aqui: https://github.com/training-center/brand-guide

**Comment by adeonir** [comment]
Oi gente, desculpa a demora, tá corrido aqui.

O logo em diversos formatos e tamanhos, além da paleta de cores, então nesse repositório que a @alinebastos postou aí...

**Comment by angeliski** [comment]
Show! Obrigado pelo apoio @alinebastos  e @adeonir 
Então podemos encerrar essa Issue?

**Comment by adeonir** [comment]
Acredito que sim. Qualquer coisa reabrimos ou criamos outra.
