### ISSUE TITLE
Gerenciamento de dados

### ISSUE THREAD

**Issue by bernardodiasc** [training-center/R2D2#42]
(vou resumir e editar depois quando tiver mais tempo)

Pra fazer o front do app, vamos ter os dados (#40), certo? Todo o objetivo desse app existir é primariamente mostrar dados, e depois prover meios de interagir com eles, basicamente. Existem muitas maneiras diferentes de gerenciar dados, muitas técnicas, muitas ferramentas, etc. Cada qual com suas peculiaridades que a tornam boa ou má escolha. O que define se é boa ou má não é o trend do twitter, mas as características do projeto. A ideia dessa issue é discutir isso e chegar a alguma conclusão, toda ideia é bem vinda e vamos juntos aprendendo.

**Comment by bernardodiasc** [comment]
Algumas técnicas e ferramentas que conheço, seus prós e cons:

## MobX

- https://github.com/mobxjs/mobx

> nunca usei, mas li bastante os docs, votaria por ele para esse projeto, mas sem experiencia nenhuma prefiro saber de quem ja usou.

## Redux

- http://redux.js.org/

> ja usei bastante, algumas configuraçoes sao um pé no saco, existe diversas libs por ai afora que prometem simplificar e as vezes complicam mais a longo prazo, ainda assim toda a sintaxe pode ser bem verbosa. porem o conceito é fenomenal e funciona muito bem, é um estado global que sofre alteracoes a partir de acoes, simples e bem "humano" (UX), por assim dizer.
> pra recomendar esse metodo, seria importante que o time de design estivesse ciente, pois nao tem nada pior do que os setores de desenvolvimento tratando os dados como universos paralelos. os dados passam por todas as etapas e aqui no front o redux tambem é usado para gerenciar o estado visual do aplicativo.

## React component state

- https://reactjs.org/docs/state-and-lifecycle.html
- https://facebook.github.io/react-vr/docs/components-props-and-state.html

> quando estava usando react, logo de cara ja havia redux instalado. nao conseguia entender pra que? entao fiz um app prototipo em react sem redux, e estressando o volume de dados e funcionalidades pude notar qual o problema que o redux soluciona.
> minha conclusao é que dá pra fazer um app inteiro sem redux ou mobx, apenas usando o state de um componente superior e deixar isso bem documentado e limpo da pra manter de buenas. mas se as rotas, estados e acoes forem muitos ai não rola ficar só nisso.

**Comment by fernandofleury** [comment]
eu já botei redux no projeto logo quando iniciei... no fim é uma mistura de redux com two-way data binding pros forms.

**Comment by bernardodiasc** [comment]
Boa! Então ta resolvido 🚀
