### ISSUE TITLE
Sugestão em mais um requisito não funcional.

### ISSUE THREAD

**Issue by macchico** [training-center/R2D2#7]
Poderia haver uma maneira dos mentores(as) e mentorados(as) (principalmente), terem como ver o tempo médio de resposta às solicitações de mentorias, talvez saber quais tecnologias tem mais mentores e são mais rapidamente atendidas. Não sei se cabe no projeto mas, at least I tried, rs.

**Comment by woliveiras** [comment]
Muito interessante, @macchico!

Isso ajudaria a pessoa a não se frustrar por conta da ansiedade.

**Comment by lflimeira** [comment]
Acho que lidar com tempo é complicado, pois ele é muito relativo, mas talvez tenha como mostrar a fila.

**Comment by khaosdoctor** [comment]
Eu concordo com o @lflimeira porque mostrar um tempo médio vai fazer aquelas filas com tempo médio menor aumentarem cada vez mais enquanto ninguém vai querer ir para as filas com tempo médio maior

**Comment by odilton** [comment]
Só uma obs. Não necessariamente o próximo da fila será o chamado, correto? Uma das coisas que tenho visto e acho excelente é que os mentorados podem criar um certo vínculo com algum mentor pelo Slack e isso acabar adiantando as coisas. Isso é, quem está precisando de mentoria correu atrás e conseguiu um mentor pela troca de ideia no Slack.

**Comment by lflimeira** [comment]
@odilton O correto não é esse processo, deveriamos priorizar os que estão na fila a mais tempo.

**Comment by angeliski** [comment]
@lflimeira @woliveiras  Chegamos em alguma conclusão? Ou que tal colocar essa avaliação de filas para uma V2 da plataforma?

**Comment by lflimeira** [comment]
Acho que está em aberto, mas posso dar minha opinião  para tentar fechar esse assunto, eu faria as implementações para pegar a data de inscrição  (data de entrada na fila) e data de início de mentoria. Com isso podemos fazer implementações dessas no futuro e nos podemos tirar métricas com esses dados para tomar medidas, mas sem mostrar tempo médio para o mentorado em um primeiro momento.

O que vcs acham? Faz sentido?

@khaosdoctor @woliveiras @angeliski

**Comment by khaosdoctor** [comment]
Faz total sentido @lflimeira! Acho que podemos criar métricas internas nessa V1 para podermos construir uma análise mais robusta na V2 mostrando dashboards e tal. Podemos tentar fixar uma regra de negócio que mentores só podem pegar mentorados se eles forem mais antigos na fila, para podermos matar quem está já a muito tempo e reduzir a quantidade

**Comment by lflimeira** [comment]
Perfeito... concordo!!!

**Comment by khaosdoctor** [comment]
Alguém tem que escrever um documento disso tudo... Documentar só em issue não vai rolar

**Comment by angeliski** [comment]
Concordo @khaosdoctor . Mas acho que essa informação é mais relevante no [hades](https://github.com/training-center/hades) do que aqui. Vou montar um PR lá

**Comment by lflimeira** [comment]
Considerando que está devidamente documentado eu vou fechar essa issue 😃
